### ISSUE TITLE
VirtualizationInformation event jdk11 support not shown

### ISSUE THREAD

**Issue by MBaesken** [parttimenerd/jfreventcollector#1]
The VirtualizationInformation event says jdk13 plus
https://sap.github.io/SapMachine/jfrevents/20.html#virtualizationinformation
but it has been backported long time ago to jdk11, see
https://github.com/openjdk/jdk11u/blob/master/src/hotspot/share/jfr/metadata/metadata.xml#L618

It looks like the current display does not take into account that some events might be in jdk13+, but also in the LTS release jdk11.

**Comment by parttimenerd** [comment]
My data set for JDK 11 does not include it, but I'd have to investigate why.

**Comment by parttimenerd** [comment]
The reason is that my releaser script did not pull the latest tag of every repository, as the GitHub API worked differently than I expected.
